### ISSUE TITLE
Takes forever to heat up and then starts cooling during printing

### ISSUE THREAD

**Issue by EdParker007** [Nickjallday/XVICO-X3s-Marlin#1]
I just installed the XVICO.bin file to my X3s printer and let it run. Installed okay.
When I try to print a file, the following happens.
1. Heats up bed properly
2. Heats up hotend to temp but hovers there for about five minutes and doesn't do anything.
3. After a few minutes, it starts printing but the temperate starts to drop as the hotend and heatbed reset to zero.
4. I have to pause print and then manually set the temps back to 200/60 at which I resume the print and it will print fine.
I have tried this multiple times with the safe thing happening. I even deleted the printer from Cura and started with a fresh profile (using Ender 3 settings).

Additional note: I even added the:
M190 S60 
M109 S200
variables to the Cura profile and it still resets to 0/0 before printing.
Sorry if I'm a noob but I am learning.

**Comment by Nickjallday** [comment]
So I received an xvico in the mail the a few weeks with this issue because I couldn’t fix this issue with 20% of the x3s out there. Give me a few days I should have an update. I think it’s mostly related to how the cold end fan blows all over the hotend. So it’s always fighting itself to stay hot. I’m working on it. In the mean time look up marlin PID tuneing. And give it a tune it should “fix” your problem with the current version.

**Comment by Nickjallday** [comment]
Also check the heater wires are in the board connectors real good, some peoples issues were solved just but tightening those two screws that hold the heater wires

**Comment by EdParker007** [comment]
Thanks for the feedback. I did run the sequence of M303 to PID train it. Still having same problem. There wasn't much fluctuation on the stock firmware but I do notice temps ranging from 197-205 when manually set to 200.

**Comment by Nickjallday** [comment]
So the printer i mentioned above had a loose ground heater wire that allowed it to sorta heat but my temps were semi inconsistent. I also messed around with the firmware after your comment tonight and got my xivco x3s rock solid temps (or as rock solid as they can be with a fan blowing on the hotend) try the firmware / .bin i just pushed it SHOULD fix your issue.

**Comment by EdParker007** [comment]
I'll give it a shot. Thanks :)

**Comment by EdParker007** [comment]
Excellent work!  That appears to have solve the problem. Thanks for the quick response!
